volumes:
  # The location of the installed ops - ops places images under this dir
  - local: /Users/[user]/.ops/
    # In the container the ops dir will be /root/.ops
    container: /root/.ops
  - local: /Users/[user]/.ops/deploy_config
    container: /config
# Ops uses environment variables in its operation. This can be handled here.
env:
  - key:
    value:
