volumes:
  - local: /Users/ian/.ops/
    container: /root/.ops
    rw: true
  - local: /Users/ian/.gcp/env/project-123456-a4567x2002h7.json
    container: /config
    rw: false
env:
  - key:
    value:
